#!/usr/bin/env sh

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

echo $1 <&0

#>&2 echo '{ "version": { ref: "'$BUILD_ID'" }}'
#>&2 echo '{ "version": { ref: "'printenv'" }}'
