---
resource_types:
- name: ansible-playbook
  type: docker-image
  source:
    repository: thesec/ansibleconcourseresource
    tag: latest

resources:
- name: 1m
  type: time
  source: {interval: 1m}

- name: git-concourse-build-docker-image
  type: git
  source:
    uri: "https://github.com/The-Sec/ansibleconcourseresource"
    #branch: master

- name: docker-image
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: {{docker-create-concourse-go-image}}

- name: ansible
  type: ansible-playbook
  source:
    debug: true
    verbose: v

jobs:
- name: build-docker-image
  public: true
  serial: true
  plan:
  - get: git-concourse-build-docker-image
    trigger: true
  - put: docker-image
    params: {build: git-concourse-build-docker-image}

- name: test-flight
  plan:
  - get: docker-image
    passed: [build-docker-image]
    trigger: true
  - get: git-concourse-build-docker-image
    passed: [build-docker-image]
  - get: 1m
    trigger: true
  - put: ansible
